/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as expiryExpiryRouteRouteImport } from './routes/(expiry)/expiry/route'
import { Route as expiryExpiryNewRouteRouteImport } from './routes/(expiry)/expiry_.new/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const expiryExpiryRouteRoute = expiryExpiryRouteRouteImport.update({
  id: '/(expiry)/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const expiryExpiryNewRouteRoute = expiryExpiryNewRouteRouteImport.update({
  id: '/(expiry)/expiry_/new',
  path: '/expiry/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expiry': typeof expiryExpiryRouteRoute
  '/expiry/new': typeof expiryExpiryNewRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expiry': typeof expiryExpiryRouteRoute
  '/expiry/new': typeof expiryExpiryNewRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(expiry)/expiry': typeof expiryExpiryRouteRoute
  '/(expiry)/expiry_/new': typeof expiryExpiryNewRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/expiry' | '/expiry/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/expiry' | '/expiry/new'
  id: '__root__' | '/' | '/(expiry)/expiry' | '/(expiry)/expiry_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  expiryExpiryRouteRoute: typeof expiryExpiryRouteRoute
  expiryExpiryNewRouteRoute: typeof expiryExpiryNewRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(expiry)/expiry': {
      id: '/(expiry)/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof expiryExpiryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(expiry)/expiry_/new': {
      id: '/(expiry)/expiry_/new'
      path: '/expiry/new'
      fullPath: '/expiry/new'
      preLoaderRoute: typeof expiryExpiryNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  expiryExpiryRouteRoute: expiryExpiryRouteRoute,
  expiryExpiryNewRouteRoute: expiryExpiryNewRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
