/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChoresRouteRouteImport } from './routes/chores/route'
import { Route as AppliancesRouteRouteImport } from './routes/appliances/route'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as expiryExpiryRouteRouteImport } from './routes/(expiry)/expiry/route'

const ChoresRouteRoute = ChoresRouteRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliancesRouteRoute = AppliancesRouteRouteImport.update({
  id: '/appliances',
  path: '/appliances',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const expiryExpiryRouteRoute = expiryExpiryRouteRouteImport.update({
  id: '/(expiry)/expiry',
  path: '/expiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/appliances': typeof AppliancesRouteRoute
  '/chores': typeof ChoresRouteRoute
  '/expiry': typeof expiryExpiryRouteRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesByTo {
  '/appliances': typeof AppliancesRouteRoute
  '/chores': typeof ChoresRouteRoute
  '/expiry': typeof expiryExpiryRouteRoute
  '/': typeof homeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/appliances': typeof AppliancesRouteRoute
  '/chores': typeof ChoresRouteRoute
  '/(expiry)/expiry': typeof expiryExpiryRouteRoute
  '/(home)/': typeof homeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/appliances' | '/chores' | '/expiry' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/appliances' | '/chores' | '/expiry' | '/'
  id: '__root__' | '/appliances' | '/chores' | '/(expiry)/expiry' | '/(home)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppliancesRouteRoute: typeof AppliancesRouteRoute
  ChoresRouteRoute: typeof ChoresRouteRoute
  expiryExpiryRouteRoute: typeof expiryExpiryRouteRoute
  homeIndexRoute: typeof homeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appliances': {
      id: '/appliances'
      path: '/appliances'
      fullPath: '/appliances'
      preLoaderRoute: typeof AppliancesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(expiry)/expiry': {
      id: '/(expiry)/expiry'
      path: '/expiry'
      fullPath: '/expiry'
      preLoaderRoute: typeof expiryExpiryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppliancesRouteRoute: AppliancesRouteRoute,
  ChoresRouteRoute: ChoresRouteRoute,
  expiryExpiryRouteRoute: expiryExpiryRouteRoute,
  homeIndexRoute: homeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
